### ISSUE TITLE
License for project?

### ISSUE THREAD

**Issue by barbeau** [metabrainz/musicbrainz-android#49]
The only reference to a software license for this project I can find is in the header for [SingleLiveEvent](https://github.com/metabrainz/musicbrainz-android/blob/f4c8cc7e7d9626fdb223c6b4a8095b5325af8a79/app/src/main/java/org/metabrainz/mobile/util/SingleLiveEvent.java), which appears to be a copy/paste from another project.

What open-source software license is the code in this project licensed under?

Thanks in advance!

**Comment by amCap1712** [comment]
@barbeau Sorry, for the late reply. (It seems my notifications were disabled :p) The License for the project is GPLv3 as you can see [here](https://musicbrainz.org/doc/MusicBrainz_for_Android) . But it is due to some of the code, the current app inherited from the previous one. Once, we get rid of the old code we are willing to change the license to a less restrictive one.
